### ISSUE TITLE
[DILogin] Handle Users with Discriminator

### ISSUE THREAD

**Issue by ezeholz** [Alhxe/Discord-Integration#12]
HI!
I've been using your plugin for a couple days now, and in code I don't see a handling of `user#0000` in registration.
My partners would really use it, and you can still using discord's ID if you handle it correctly.

I could manage to work it out in a few days, but I don't know the code and it's taking me such a lot of time to figure it out.
Nice plugin! Hope to see other implementations that you had in mind.

**Comment by Alhxe** [comment]
Hello, at the beginning of the year I will try to make all the suggestions that have been added by Discord and here.

I appreciate the opinion and your suggestion.

**Comment by Alhxe** [comment]
Added in 2.4.1 version
