### ISSUE TITLE
Enable/Disable Plugin

### ISSUE THREAD

**Issue by Silvobi** [Alhxe/Discord-Integration#15]
Could be really useful if I could enable or disable plugin during the server is ON

imagine the situation - server is under bot attack
you switch the plugin and now only verificated players can join

**Comment by authorless** [comment]
In this case, it is better to use the Ultimate Anti Bot plugin, which, with a good setup, copes with this task perfectly

**Comment by Alhxe** [comment]
The function of the plugin is a login system. There is no point in disabling the login method, since any user could access the server. You should have some plugin that prevents attacks.
