### ISSUE TITLE
the ability to send messages even when it does not confirm the login to the account

### ISSUE THREAD

**Issue by hilltty** [Alhxe/Discord-Integration#16]

**Comment by Alhxe** [comment]
You specify how it would work exactly

**Comment by hilltty** [comment]
I didn't quite understand your question, sorry
until the entry is confirmed by pressing the reaction under the bot message, the player's messages in the chat should not be sent

**Comment by Alhxe** [comment]
Right now, messages in chat are not sent until the login or registration is confirmed. If not, show me an example.

**Comment by hilltty** [comment]
![image](https://user-images.githubusercontent.com/49129010/186925875-439cd408-6c5d-4b47-890e-505e9a69e47d.png)

**Comment by Alhxe** [comment]
I don't experience that problem, what plugins are you using

**Comment by hilltty** [comment]
I'm currently using this plugin, but I'm not sure if it's the problem?
https://www.spigotmc.org/resources/rpchat-ntd-1-12-1-19-head-chat-%E2%9A%A1-scoreboard-dm-%E2%9A%A1-hoverable-chat-%E2%9A%A1-rp-commands-%E2%9A%A1-oraxen-support.94516/

**Comment by Alhxe** [comment]
Try to start the server without that plugin and see if u can chat

**Comment by hilltty** [comment]
yes, the problem is in the plugin, sorry, I will write to the developer
