### ISSUE TITLE
Text formatting error

### ISSUE THREAD

**Issue by hilltty** [Alhxe/Discord-Integration#17]
after some messages from the plugin, "diregister <discord_id>" appears, which does not belong there at all

video: https://youtu.be/wPDRv1th_00

**Comment by Alhxe** [comment]
Being in Russian I don't understand very well what is happening in the video...

**Comment by hilltty** [comment]
What does it look like in config
`register_user_not_detected: "some message for u <3"`
and what it looks like in the game
![image](https://user-images.githubusercontent.com/49129010/186749325-67acca4a-6e78-4538-90df-cad3f01ecf18.png)

**Comment by Alhxe** [comment]
So i have to remove the "diregister <discord_id>" ?

**Comment by hilltty** [comment]
yes, I don't quite understand why this message appears.

**Comment by Alhxe** [comment]
Fixed in next version (2.4.4)
