### ISSUE TITLE
The status online set in Discord SRV is not displayed

### ISSUE THREAD

**Issue by defojeco** [Alhxe/Discord-Integration#18]
The online status set in Discord SRV is not displayed, it is replaced with online, regardless of what you have set.

**Comment by Alhxe** [comment]
Good afternoon, I do not experience the problem.
Having dicore's bot-status set to 0, the bot's status stays as DiscordSRV.

![image](https://user-images.githubusercontent.com/20838594/187032674-cb6a64a8-685c-46f8-8dd0-e18d9026765e.png)

**Comment by defojeco** [comment]
![image](https://user-images.githubusercontent.com/75880801/187039975-59a7aaad-7fe0-4d48-9a1f-469809d413a8.png)
So, I am in the SRV configuration, set the value of DiscordOnlineStatus:IDLE , but it is displayed as online, if I delete Dicore, it will be as it should
![image](https://user-images.githubusercontent.com/75880801/187040157-0ea8af9b-4a33-4331-946b-efc58fdf6302.png)
![image](https://user-images.githubusercontent.com/75880801/187040215-3e88efad-8be5-42f6-8e40-0f10b0f525ec.png)

**Comment by Alhxe** [comment]
Non reported other new cases
