### ISSUE TITLE
please add newline support to lang config

### ISSUE THREAD

**Issue by TheMrMes109** [Alhxe/Discord-Integration#2]
\n and %nl% the plugin does not work, it is necessary that everything that is half \n starts on a new line in the chat) thanks in advance: 3

&c&l◊ &fTo link this account with your Discord user &c&l◊ \n &c&l◊ &f &fuse the &f%register_command% &fcommand on our Discord server &c&l◊

**◊** To link this account with your Discord user **◊**
**◊** use the +register 'CODE' command on our Discord server **◊**

**Comment by Alhxe** [comment]
In the next version it will be added. I hope it's ready between tomorrow and the day after.

**Comment by Alhxe** [comment]
To solve the problem you only need to change the single quotes to double quotes. In the next version the language files will be updated, you can try to do it in the meantime.

As an example: `"&cTo register, use the command &6%register_command% \n &con our discord server or use here &6/register <discord_id>"` it would have a line break in the middle.

**Comment by TheMrMes109** [comment]
Thanks, everything works with "

**Comment by Alhxe** [comment]
Perfect!
