### ISSUE TITLE
The session is reset after the server is restarted

### ISSUE THREAD

**Issue by forditt** [Alhxe/Discord-Integration#22]
Regardless of the specified time of the session, it always ends after the server is restarted, in my opinion this is very interferes. Is it possible to simply output such an option in the configuration file?

**Comment by Alhxe** [comment]
I can analyze it. Sessions are not saved for data protection reasons, maybe in the next version I will add that possibility, encrypting the IP address.

**Comment by Reeferx7** [comment]
Very good idea, also if possible add config option to end the session only if IP change without time needed.

**Comment by Alhxe** [comment]
It is done in the commit 048eadc
