### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by Energobro** [Alhxe/Discord-Integration#23]
I want to build DiLogin for my needs, I didn’t touch anything much and the plugin just doesn’t build due to an error in pom.xml

[ERROR] Failed to execute goal on project dilogin: Could not resolve dependencies for project com.diproject:dilogin:jar:4.0.3: com.diproject:dicore:jar:4.0.3 was not found in https://repo.codemc.org/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of codemc-repo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

If you know what the problem is please let me know

**Comment by Alhxe** [comment]
You only have to do a mvn clean install in the parent POM of the project. The build would run like this:

internal
dicore
dilogin
dilitebanslogs

They're local projects, you cant find on https://repo.codemc.org/repository/maven-public/.

**Comment by Energobro** [comment]
And how can I compile? The fact that everything must be compiled separately, I understood, I just did not understand a little how

**Comment by Alhxe** [comment]
No need to compile separately... Simply in the main folder of the project, where all the modules and that POM are, open the windows/linux console in that path, and run mvn clean install
![image](https://user-images.githubusercontent.com/20838594/218331313-f50e25ae-48d8-422d-bb5c-b643c6c1a166.png)

**Comment by Energobro** [comment]
![image](https://user-images.githubusercontent.com/61550676/218331712-deed140e-b843-4a97-8d5b-df041aa26d8d.png)
Translation: mvn is not an internal command. I don’t understand a little how to compile this because I didn’t have experience before, sorry

**Comment by Energobro** [comment]
![image](https://user-images.githubusercontent.com/61550676/218331966-07d9bb71-12bf-41c6-8500-994407ce9706.png)
Where is it compiled?

**Comment by Alhxe** [comment]
Your compilation is in target folder, example PROJECT_MAIN_FOLDER/dilogin/target
