### ISSUE TITLE
Suggestion slash commands and button

### ISSUE THREAD

**Issue by candied-apple** [Alhxe/Discord-Integration#25]
Usage of slash commands and buttons instead of reactions in discord.

**Comment by candied-apple** [comment]
Maybe you can type the Login text on screen like  title command.
You can send this message every 3 seconds until user login.
![image](https://github.com/Alhxe/Discord-Integration/assets/50497574/90116949-7554-4c2d-98e7-fb681603115c)

**Comment by Alhxe** [comment]
I'm sorry I don't answer at this time, but I barely have time in my life to live outside of work and studies.
When I have time, I will try to find out this topic. I know that slash commands are more useful and showy.

**Comment by Alhxe** [comment]
Slash commands are avaiable on the beta https://github.com/Alhxe/Discord-Integration/releases/tag/4.3.1-beta2
