### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by RaymondChang1204** [Alhxe/Discord-Integration#29]
hello this is chinese translate
is dtlogin
[lang_zh.txt](https://github.com/Alhxe/Discord-Integration/files/11765849/lang_zh.txt)
is dtcore
[lang_zh.txt](https://github.com/Alhxe/Discord-Integration/files/11765855/lang_zh.txt)
please change suffix do yml

**Comment by Alhxe** [comment]
Translation has been created on Discord https://discordapp.com/channels/889212731289374750/1119212307482943518

**Comment by RaymondChang1204** [comment]
my discord id is RC Raymond
