### ISSUE TITLE
DILogin not working on 1.17 

### ISSUE THREAD

**Issue by hilltty** [Alhxe/Discord-Integration#3]
Hi, when I try to start the server it writes an error like this: 
https://pastebin.com/LNtVWBX5

**Comment by Alhxe** [comment]
The problem you have contributed is not due to the new version.

> at di.internal.controller.file.ConfigManager.getBoolean(ConfigManager.java:47) ~[?:?]  

You are trying to access a value in the configuration file that is empty. Check if the Teleportation section has it set to false.
