### ISSUE TITLE
Player does not get role through in game registration ("register_give_role_enabled")

### ISSUE THREAD

**Issue by quillincn** [Alhxe/Discord-Integration#35]
### Server version:
- paper-1.20.1-196
### Tested plugins versions:
- dicore-4.2.0-noslf4j
- dilogin-4.2.0

- dicore-4.3.1-beta2-noslf4j
- dilogin-4.3.1-beta2
### Problem:
1. If the player registers through Discord, using `+register CODE`, he will get role from settings as expected
2. If the player is registering through the in-game command, `/register login/id`, he does not get any role from settings.

**Comment by Alhxe** [comment]
As long as I can, I review the information provided, perhaps the addition of roles is not incorporated into the flow

**Comment by quillincn** [comment]
Got it! Hope it will be easy to fix 🤞Thanks!

**Comment by Alhxe** [comment]
Solved on 4.3.1 release https://github.com/Alhxe/Discord-Integration/releases/tag/4.3.1
