### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by LosBagros** [Alhxe/Discord-Integration#5]
Hello, thanks a lot for plugin.
It helped a lot to stop griefing on my server.

But there is still smooth brains who is writing other stuff in to the registration channel.
![image](https://user-images.githubusercontent.com/45005533/126210859-72736ed6-b5fd-4c99-84ab-a8ea135acd1e.png)

Is possible that bot will delete every message in the channel and leave only message how to register.

Thanks,
Los_Bagros

**Comment by Alhxe** [comment]
That is something very concrete. The things that are done in the plugin are those that in general are going to serve everyone. You can resort to not seeing the history of the channel or things like that.
