### ISSUE TITLE
[Feature request] Nickname synchronization

### ISSUE THREAD

**Issue by shardeex** [Alhxe/Discord-Integration#8]
Hi! Thanks a lot for a plugin.

I want to suggest a feature: synchronize nicknames. For example, if I login with minecraft nickname 'shardeex', but my Discord username is 'some weird username', bot gives me nickname 'shardeex' on server.

(also, you have expired discord link in readme.md)

**Comment by Alhxe** [comment]
Thanks for your suggestion! Tomorrow i will work on it.
I have created a new server to support

https://discord.gg/CT2vvQwkb5

**Comment by Alhxe** [comment]
Done in 2.1.2 version.
